name: Deploy Java App to Dev Servers
on:
  push:
    paths-ignore:
      - "js/**"
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        # script: pkill java && pkill screen && cd git/gathering && git pull && screen -d -m java -jar --enable-preview java/target/gathering-0.0.1-SNAPSHOT.jar
        script: cd git/gathering && git pull && screen -d -m java -jar --enable-preview java/target/gathering-0.0.1-SNAPSHOT.jar
