name: Deploy Java App to Dev Server
on:
  push:
    paths-ignore:
      - "js/**"
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: log onto dev server, kill old javaApp screen, start new one
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: pkill -f .*javaApp >/dev/null && cd git/gathering/java && git pull -q -f && mvn clean package && screen -S javaApp -d -m java -jar --enable-preview target/gathering-0.0.1-SNAPSHOT.jar
