name: Deploy Java App to Dev Server
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        port: 22
        script: kill $(jps | grep gathering | awk '{print $1}') && cd git/gathering && git pull && java -jar --enable-preview java/target/gathering-0.0.1-SNAPSHOT.jar &
