name: Deploy React App to Dev Server
defaults:
  run:
    working-directory: ./js
on:
  push:
    paths-ignore:
      - "java/**"
    branches:
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: log onto dev server, kill old reactApp screen, start new one
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        script: pkill -f .*reactApp >/dev/null && cd git/gathering/js && git pull -q -f && npm-install-changed >/dev/null && rm -f .env && echo REACT_APP_DEV_SERVER_ADDRESS=${{ secrets.SERVER_HOST }} >> .env && screen -S reactApp -d -m npm start
